AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ocean Catalog

Parameters:
  BucketName:
    Type: String
    Description: Enter the S3 bucket name for the lake.
    Default: mytiki-ocean
  DatabaseName:
    Type: String
    Description: Enter the database name for the lake.
    Default: ocean

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  Glue:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref DatabaseName
        Description: Metadata catalog for Ocean
        LocationUri: !Sub "s3://${BucketName}"
