version = 0.1
[default.deploy.parameters]
stack_name = "ocean-catalog"
s3_bucket = "mytiki-sam-deploy"
s3_prefix = "ocean/catalog"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "BucketName=mytiki-ocean DatabaseName=ocean"
