AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ocean - Catalog Infrastructure

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ..
      Handler: com.mytiki.ocean.catalog.App::handleRequest
      Runtime: java17
      Architectures:
        - arm64
      MemorySize: 512
      Timeout: 20
      FunctionUrlConfig:
        AuthType: NONE
        InvokeMode: BUFFERED
        Cors:
          AllowCredentials: true
          MaxAge: 0
          AllowHeaders:
            - Authorization
            - Content-Type
            - Accept
          AllowMethods:
            - GET
            - POST
            - DELETE
          AllowOrigins:
            - "*"
      Policies:
        - S3WritePolicy:
            BucketName: "mytiki-ocean"
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - glue:GetTable
                - glue:GetDatabase
                - glue:CreateTable
              Resource:
                - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:catalog"
                - !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:database/ocean"
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - glue:GetTable
                - glue:CreateTable
              Resource: !Sub "arn:aws:glue:${AWS::Region}:${AWS::AccountId}:table/ocean/*"

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mytiki-ocean

  Glue:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: ocean
        Description: Metadata catalog for Ocean
        LocationUri: s3://mytiki-ocean

Outputs:
  FunctionUrl:
    Description: "URL"
    Value: !GetAtt FunctionUrl.FunctionUrl

  Bucket:
    Description: "ARN"
    Value: !GetAtt Bucket.Arn

  Glue:
    Description: "Name"
    Value: !Ref Glue

