AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Ocean-Catalog S3 Bucket

Parameters:
  BucketName:
    Type: String
    Description: Enter the S3 bucket name for the lake.

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
