version = 0.1

[default.global.parameters]
stack_name = "ocean-catalog-aws"
s3_bucket = "mytiki-sam-deploy"
s3_prefix = "ocean/catalog/aws"
region = "us-east-2"

[default.deploy.parameters]
confirm_changeset = false
capabilities = [
    "CAPABILITY_IAM",
    "CAPABILITY_AUTO_EXPAND"
]
image_repositories = []
parameter_overrides = [
    "BucketName=mytiki-cleanroom-sample",
    "DatabaseName=cleanroom-sample"
]
